### ISSUE TITLE
Unable to start notebook using the docker image (GPU) in windows 10 machine

### ISSUE THREAD

**Issue by similang** [Kaggle/docker-python#1129]
## 🐛 Bug

Unable to start jupyter using the docker image (GPU) in Windows 10 machine

### Additional context

[E 2022-02-08 09:11:28.475 ServerApp](B Exception while loading config file /opt/jupyter/.jupyter/jupyter_notebook_config.py

    Traceback (most recent call last):

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn

        (self._dns_host, self.port), self.timeout, **extra_kw

      File "/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection

        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

      File "/opt/conda/lib/python3.7/socket.py", line 752, in getaddrinfo

        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

    socket.gaierror: [Errno -3] Temporary failure in name resolution

    

    During handling of the above exception, another exception occurred:

    

    Traceback (most recent call last):

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen

        chunked=chunked,

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request

        conn.request(method, url, **httplib_request_kw)

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request

        super(HTTPConnection, self).request(method, url, body=body, headers=headers)

      File "/opt/conda/lib/python3.7/http/client.py", line 1281, in request

        self._send_request(method, url, body, headers, encode_chunked)

      File "/opt/conda/lib/python3.7/http/client.py", line 1327, in _send_request

        self.endheaders(body, encode_chunked=encode_chunked)

      File "/opt/conda/lib/python3.7/http/client.py", line 1276, in endheaders

        self._send_output(message_body, encode_chunked=encode_chunked)

      File "/opt/conda/lib/python3.7/http/client.py", line 1036, in _send_output

        self.send(msg)

      File "/opt/conda/lib/python3.7/http/client.py", line 976, in send

        self.connect()

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect

        conn = self._new_conn()

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn

        self, "Failed to establish a new connection: %s" % e

    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f41d562c9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

    

    During handling of the above exception, another exception occurred:

    

    Traceback (most recent call last):

      File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 449, in send

        timeout=timeout

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen

        **response_kw

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen

        **response_kw

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen

        **response_kw

      [Previous line repeated 2 more times]

      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen

        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

      File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment

        raise MaxRetryError(_pool, url, error or ResponseError(cause))

    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='metadata', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/use-collaborative (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f41d562c9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

    

    During handling of the above exception, another exception occurred:

    

    Traceback (most recent call last):

      File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 738, in _load_config_files

        config = loader.load_config()

      File "/opt/conda/lib/python3.7/site-packages/traitlets/config/loader.py", line 614, in load_config

        self._read_file_as_dict()

      File "/opt/conda/lib/python3.7/site-packages/traitlets/config/loader.py", line 646, in _read_file_as_dict

        exec(compile(f.read(), conf_filename, 'exec'), namespace, namespace)

      File "/opt/jupyter/.jupyter/jupyter_notebook_config.py", line 144, in <module>

        if get_metadata_value('use-collaborative'):

      File "/opt/jupyter/.jupyter/jupyter_notebook_config.py", line 56, in get_metadata_value

        headers=METADATA_FLAVOR,

      File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 555, in get

        return self.request('GET', url, **kwargs)

      File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 542, in request

        resp = self.send(prep, **send_kwargs)

      File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 655, in send

        r = adapter.send(request, **kwargs)

      File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 516, in send

        raise ConnectionError(e, request=request)

    requests.exceptions.ConnectionError: HTTPConnectionPool(host='metadata', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/use-collaborative (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f41d562c9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

/opt/conda/lib/python3.7/site-packages/jupyter_server_mathjax/app.py:40: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.

  help=_("""The MathJax.js configuration file that is to be used."""),

**Comment by djherbis** [comment]
Can you provide the full docker command and other commands you ran?

**Comment by similang** [comment]
> Can you provide the full docker command and other commands you ran?

Hi,

Sorry for late response.

I actually just followed the tutorial here. 

https://hkalabs.com/blog/tips-n-tricks-cara-menginstall-menggunakan-docker-kaggle-python-windows-10/

So basically the steps are replicated from this using Docker Desktop on my personal PC.

I don't see there's any tutorial on windows 10 using Docker Desktop to use the Kaggle Python GPU Image. Do let me know if any.


Regards.

**Comment by similang** [comment]
> Can you provide the full docker command and other commands you ran?

Would the link I provided above helpful for diagnosis of the problem?

**Comment by similang** [comment]
Any updates 🥺

**Comment by djherbis** [comment]
@similang The link you provided is for a CPU notebook not a GPU one, and the errors your container is showing look like network errors.

I can't really follow the link you shared. It normally should be fairly straightforward to just run the docker image with a couple ports open and then run the jupyter notebook server inside the container.

```
docker run -p 9012:9012 -it gcr.io/kaggle-gpu-images/python bash
> jupyter notebook  --no-browser --port 9012 --allow-root --ip 0.0.0.0
```

Connect at localhost:9012

That won't actually leverage your local GPU though, just load the GPU image.
You can try adding the `-gpus all` flag to docker run, though I'm not sure how that will work on windows.

**Comment by similang** [comment]
On the side note, thanks as I managed to get a look within the image but it's still not detecting my GPU with the script you provided above.
