### ISSUE TITLE
NameError: name 'io' is not defined

### ISSUE THREAD

**Issue by nutorbit** [Kaggle/docker-python#1324]
## 🐛 Bug

I am trying to run my scripts on GPU notebook, and I keep getting the following error.

```shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1172, in init
    getcaller()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 846, in getcaller
    src, line, func, stack = logger.findCaller(stack_info=True)
  File "/root/.local/lib/python3.10/site-packages/log.py", line 42, in findCaller
    sio = io.StringIO()
NameError: name 'io' is not defined
```

In addition, I found that there is no import `io` package in [this](https://github.com/Kaggle/docker-python/blob/main/patches/log.py) code.

**Comment by Philmod** [comment]
Please add more context on how to reproduce the problem.
