### ISSUE TITLE
pip failing in docker image

### ISSUE THREAD

**Issue by slundberg** [Kaggle/docker-python#188]
```
> docker run --rm -it kaggle/python
Unable to find image 'kaggle/python:latest' locally
latest: Pulling from kaggle/python
85b1f47fba49: Pull complete 
603f9c6eacba: Pull complete 
501f1d57b2bc: Pull complete 
6db69dab30a3: Pull complete 
e59a3b870714: Pull complete 
deb1469423f3: Pull complete 
603f965ef7ff: Pull complete 
a220077a9d0b: Pull complete 
518e35fe71ee: Pull complete 
aca9c2ba4b65: Pull complete 
1cd17eef77cd: Pull complete 
6830763063dc: Pull complete 
c1d2677a9331: Pull complete 
aed6ee813799: Pull complete 
e4992a4929c7: Pull complete 
Digest: sha256:0f4089a83e4f38898dc3a50aa6c756cbefaf8a25ec5811917257a60099c5af16
Status: Downloaded newer image for kaggle/python:latest
root@1a863fee85cc:/# pip
Traceback (most recent call last):
  File "/opt/conda/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/conda/lib/python3.6/site-packages/pip/__init__.py", line 2, in <module>
    from __future__ import absolute_import
ValueError: source code string cannot contain null bytes
root@1a863fee85cc:/# 
```

Just trying to follow the instructions in the README. In case it matters I did this on OSX.

**Comment by slundberg** [comment]
I tried months later on an Ubuntu machine and it worked. Perhaps something changed in the meantime with the image that fixed it.
