### ISSUE TITLE
ModuleNotFoundError: No module named 'skimage'

### ISSUE THREAD

**Issue by Ishitori** [Kaggle/docker-python#452]
I want to add MXNet (GPU version), GluonNLP and GluonCV packages to docker file. But if I just try to build original dockerfile by running `./build` I get `ModuleNotFoundError: No module named 'skimage'`.

```
Collecting git+git://github.com/scikit-image/scikit-image@31d9ecc2f0d8dd3373af3e80b2dcc7887ff2ca24
  Cloning git://github.com/scikit-image/scikit-image (to revision 31d9ecc2f0d8dd3373af3e80b2dcc7887ff2ca24) to /tmp/pip-req-build-5sjsxjj4
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command /opt/conda/bin/python /opt/conda/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp0yeyn_a9:
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 222, in <module>
      **extra
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/distutils/core.py", line 137, in setup
      config = configuration()
    File "setup.py", line 137, in configuration
      config.add_subpackage('skimage')
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1036, in add_subpackage
      caller_level = 2)
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1005, in get_subpackage
      caller_level = caller_level + 1)
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "skimage/setup.py", line 9, in configuration
      config.add_subpackage('_shared')
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1036, in add_subpackage
      caller_level = 2)
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1005, in get_subpackage
      caller_level = caller_level + 1)
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 918, in _get_configuration_from_setup_py
      ('.py', 'U', 1))
    File "/tmp/pip-build-env-6hfrqkax/overlay/lib/python3.6/site-packages/numpy/compat/py3k.py", line 147, in npy_load_module
      return importlib.machinery.SourceFileLoader(name, fn).load_module()
    File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
    File "<frozen importlib._bootstrap_external>", line 823, in load_module
    File "<frozen importlib._bootstrap_external>", line 682, in load_module
    File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
    File "<frozen importlib._bootstrap>", line 684, in _load
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "skimage/_shared/setup.py", line 5, in <module>
      from skimage._build import cython
  ModuleNotFoundError: No module named 'skimage'

```
Is there something I should do differently? 
Thanks.

**Comment by jpzhangvincent** [comment]
I have the issue when building the CPU version of docker image.

**Comment by rosbo** [comment]
Hi, we are actively working on fix the CPU build. Stay tuned.

**Comment by rosbo** [comment]
The CPU build is now fixed.

**Comment by jpzhangvincent** [comment]
just curious, is the fix pushed?

**Comment by rosbo** [comment]
Yes, the fix has been pushed to the `master` branch. Are you still having issue when running `./build` fetching the latest changes from `master`? If yes, can you include the build error you are getting.

Thank you
