### ISSUE TITLE
Kernels are failing to run after latest updates

### ISSUE THREAD

**Issue by AdityaSoni19031997** [Kaggle/docker-python#520]
- There's a file named core getting dumped to the output section after the latest updates made to the kernel and as a result it runs out of space since that file is more than 4.5 gigs.. 
- Error like this show up sometimes as well **Unhandled exception (Error copying from/to GCS.)**

PS kaggle should never update the packages when a Kernels only comp is running as it's can brake things..

**Comment by AdityaSoni19031997** [comment]
Here's another one and i have no clue why it's happening..
```
2019-03-23 04:43:16.998403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0

2019-03-23 04:43:17.364693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-23 04:43:17.364761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-03-23 04:43:17.364775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 

2019-03-23 04:43:17.365347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15121 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)

2019-03-23 04:43:17.383603: E tensorflow/stream_executor/cuda/cuda_driver.cc:655] failed to memset memory: CUDA_ERROR_INVALID_VALUE: invalid argument

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call

    return fn(*args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn

    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to memcopy into scratch buffer for device 0
     [[{{node _SOURCE}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../src/script.py", line 2969, in <module>
    model = build_model(embedding_matrix, nb_words, focal_loss(2.75, 0.85), embedding_size)
  File "../src/script.py", line 2831, in build_model

    x = Embedding(nb_words, embedding_size, weights=[embedding_matrix], trainable=False)(inp)
  File "/opt/conda/lib/python3.6/site-packages/keras/engine/base_layer.py", line 436, in __call__

    self.set_weights(self._initial_weights)
  File "/opt/conda/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1051, in set_weights

    param_values = K.batch_get_value(params)
  File "/opt/conda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2420, in batch_get_value

    return get_session().run(ops)
  File "/opt/conda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 199, in get_session

    [tf.is_variable_initialized(v) for v in candidate_vars])
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to memcopy into scratch buffer for device 0
     [[{{node _SOURCE}}]]
```

**Comment by chaudharyachint08** [comment]
**Why do you closed this** 

Upon executing
**new_generator_model.load_weights(os.path.join(save_dir,gen_choice))**

**I am also getting error below**
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to memcopy into scratch buffer for device 0
         [[{{node _SOURCE}} = NoOp[]()]]
