### ISSUE TITLE
Weird validation error

### ISSUE THREAD

**Issue by ldmtwo** [Kaggle/docker-python#724]
It seems I'm getting this error. https://github.com/jupyter/nbconvert/issues/955 Maybe you just need to upgrade Jupyter?

My kernel notebook runs just fine. Only when trying to commit the code I will get an error.

The kernel isn't public, so this link is for privileged users. https://www.kaggle.com/ldmtwo/eda-rle-plots?scriptVersionId=29204157

Docker image version = latest

```
Time
#
Log Message
1.97
1
[NbConvertApp] Converting notebook __notebook__.ipynb to notebook
5.18
2
[NbConvertApp] Executing notebook with kernel: python3
67.39
3
--- Logging error ---
67.39
4
Traceback (most recent call last):
67.39
5
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
67.39
6
nbformat.validate(nbc, relax_add_props=True)
67.39
7
File "/opt/conda/lib/python3.6/site-packages/nbformat/validator.py", line 277, in validate
67.39
8
raise error
67.39
9
nbformat.validator.NotebookValidationError: {'version_major': 2, 'version_minor': 0, 'model_id': 'b95379c680e14c16992be212a3122ad6'} is not valid under any of the given schemas
67.39
10
67.39
11
Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:
67.39
12
67.39
13
On instance['cells'][7]['outputs'][1]['data']['application/vnd.jupyter.widget-view+json']:
67.39
14
{'model_id': 'b95379c680e14c16992be212a3122ad6',
67.39
15
'version_major': 2,
67.39
16
'version_minor': 0}
67.39
17
67.39
18
During handling of the above exception, another exception occurred:
67.39
19
67.39
20
Traceback (most recent call last):
67.39
21
File "/opt/conda/lib/python3.6/logging/__init__.py", line 993, in emit
67.39
22
msg = self.format(record)
67.39
23
File "/opt/conda/lib/python3.6/logging/__init__.py", line 839, in format
67.39
24
return fmt.format(record)
67.39
25
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 117, in format
67.39
26
return super(LevelFormatter, self).format(record)
67.39
27
File "/opt/conda/lib/python3.6/logging/__init__.py", line 576, in format
67.39
28
record.message = record.getMessage()
67.39
29
File "/opt/conda/lib/python3.6/logging/__init__.py", line 338, in getMessage
67.39
30
msg = msg % self.args
67.39
31
TypeError: not all arguments converted during string formatting
67.39
32
Call stack:
67.39
33
File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
67.39
34
sys.exit(main())
67.39
35
File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 268, in launch_instance
67.39
36
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
67.39
37
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
67.39
38
app.start()
67.39
39
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 340, in start
67.39
40
self.convert_notebooks()
67.39
41
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
67.39
42
self.convert_single_notebook(notebook_filename)
67.39
43
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
67.39
44
output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
67.39
45
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
67.39
46
output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
67.39
47
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
67.39
48
return self.from_file(f, resources=resources, **kw)
67.39
49
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
67.39
50
return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
67.39
51
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
67.39
52
nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
67.39
53
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
67.39
54
nb_copy, resources = self._preprocess(nb_copy, resources)
67.39
55
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 321, in _preprocess
67.39
56
preprocessor)
67.39
57
Message: 'Notebook is invalid after preprocessor {}'
67.39
58
Arguments: (<nbconvert.preprocessors.execute.ExecutePreprocessor object at 0x7f44f1c710f0>,)
67.39
59
Traceback (most recent call last):
67.39
60
File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
67.39
61
sys.exit(main())
67.39
62
File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 268, in launch_instance
67.39
63
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
67.39
64
File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
67.39
65
app.start()
67.39
66
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 340, in start
67.39
67
self.convert_notebooks()
67.39
68
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
67.39
69
self.convert_single_notebook(notebook_filename)
67.39
70
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
67.39
71
output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
67.39
72
File "/opt/conda/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
67.39
73
output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
67.39
74
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
67.39
75
return self.from_file(f, resources=resources, **kw)
67.39
76
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
67.39
77
return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
67.39
78
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
67.39
79
nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
67.39
80
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
67.39
81
nb_copy, resources = self._preprocess(nb_copy, resources)
67.39
82
File "/opt/conda/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
67.39
83
nbformat.validate(nbc, relax_add_props=True)
67.39
84
File "/opt/conda/lib/python3.6/site-packages/nbformat/validator.py", line 277, in validate
67.39
85
raise error
67.39
86
nbformat.validator.NotebookValidationError: {'version_major': 2, 'version_minor': 0, 'model_id': 'b95379c680e14c16992be212a3122ad6'} is not valid under any of the given schemas
67.39
87
67.39
88
Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:
67.39
89
67.39
90
On instance['cells'][7]['outputs'][1]['data']['application/vnd.jupyter.widget-view+json']:
67.39
91
{'model_id': 'b95379c680e14c16992be212a3122ad6',
67.39
92
'version_major': 2,
67.39
93
'version_minor': 0}
68.42
94
[NbConvertApp] Converting notebook __notebook__.ipynb to html
69.45
95
[NbConvertApp] Writing 366800 bytes to __results__.html
```

**Comment by djherbis** [comment]
I suspect you're right about needing to update nbconvert. We've received a few reports of this.
We're planning to do a new docker release soon so we'll try to include this.

**Comment by djherbis** [comment]
Looks like we're already running nbconvert 5.6.1 which is the latest release, however the fix for this was committed after this release.

We'll have to think about how to integrate it.

**Comment by djherbis** [comment]
I think this might actually be related to https://github.com/jupyter/nbformat/issues/161 and be connected to the notebooks themselves not nbconvert.

**Comment by ldmtwo** [comment]
Replying via email...
I was able to narrow down the problem to tqdm_notebook. For some reason, it did not like that. As a workaround, I redefined it as a simple pass through function when publishing. It would be great if there was a clearer message or better support for tqdm. Thanks for looking into it.

**Comment by djherbis** [comment]
I've actually copied your notebook and been using it for testing. I can get it to work by modifying the notebook metadata so I suspect it will work once I figure out how to apply my manual fixes to the system.

**Comment by djherbis** [comment]
Update, this should be fixed now:
https://www.kaggle.com/product-feedback/131993#758302
