### ISSUE TITLE
please bump LightGBM from 2.3.1 to 3.0.0

### ISSUE THREAD

**Issue by marketneutral** [Kaggle/docker-python#909]
Hi- I would make a PR for this, but I wanted to check that this is something you would accept. There are quite a few improvements from the pinned version to 3.0.0. The version 2.3.1 is over a year old. Is there a reason it hasn't been updated? This is an extremely popular library on Kaggle.

**Comment by rosbo** [comment]
Hi @marketneutral,

That would great.

IIRC we added the version pin to ensure the same version is used in CPU and GPU (we had issue when building a new image while a new LightGBM release was made available in the middle of the build).

Don't hesitate to tag me on the PR.

Thank you

**Comment by marketneutral** [comment]
Bumping to 3.1.0 causes your existing lgb tests to fail. It won't open the `data/lgb_train.bin`. This is unexpected. Perhaps they changed the binary file format. I have to investigate.

```
======================================================================
ERROR: test_cpu (test_lightgbm.TestLightgbm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/input/tests/test_lightgbm.py", line 32, in test_cpu
    early_stopping_rounds=1)
  File "/opt/conda/lib/python3.7/site-packages/lightgbm/engine.py", line 231, in train
    booster = Booster(params=params, train_set=train_set)
  File "/opt/conda/lib/python3.7/site-packages/lightgbm/basic.py", line 2053, in __init__
    train_set.construct()
  File "/opt/conda/lib/python3.7/site-packages/lightgbm/basic.py", line 1325, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/opt/conda/lib/python3.7/site-packages/lightgbm/basic.py", line 1117, in _lazy_init
    ctypes.byref(self.handle)))
  File "/opt/conda/lib/python3.7/site-packages/lightgbm/basic.py", line 55, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Input file is not LightGBM binary file

----------------------------------------------------------------------
```
